### ISSUE TITLE
ValueError(f'Units value must be one of {self.UNITS_CODES.keys()}')

### ISSUE THREAD

**Issue by dejarikbcn** [h4/lywsd02#4]
Hi,

I'm trying to read data from my sensor using your amazing lib, but I'm getting the following error. May you take a minute to help me?

Installing everythin seemts to go fine:

**pi@raspberrypi:~/python_scripts $ sudo pip3 install lywsd02**
_Collecting lywsd02
...
Successfully built bluepy
Installing collected packages: bluepy, lywsd02
Successfully installed bluepy-1.3.0 lywsd02-0.0.2_

I have my device's MAC address:

**pi@raspberrypi:~ $ sudo hcitool lescan**
_LE Scan ...
3F:5B:7D:81:45:12 LYWSD02_

However, when launching a simple test:

_from lywsd02 import Lywsd02Client
mac = '3F:5B:7D:81:45:12'
client = Lywsd02Client(mac)_

I'm always getting this exception:

**pi@raspberrypi:~/python_scripts $ sudo python3 sensortest.py**
_Traceback (most recent call last):
  File "sensortest.py", line 1, in <module>
    from lywsd02 import Lywsd02Client
  File "/usr/local/lib/python3.5/dist-packages/lywsd02/__init__.py", line 1, in <module>
    from lywsd02.client import Lywsd02Client
  **File "/usr/local/lib/python3.5/dist-packages/lywsd02/client.py", line 70
    raise ValueError(f'Units value must be one of {self.UNITS_CODES.keys()}')**
                                                                           ^
SyntaxError: invalid syntax_

Please can you help me?

Thanks!

**Comment by h4** [comment]
Hi! I'm on vacation now. I think I can fix this problem after 15th September. Sorry.

**Comment by dejarikbcn** [comment]
Hi! Thanks!!
We will be looking forward to hearing from you! :-) 👍 👍

**Comment by kasparsd** [comment]
Raspbian GNU/Linux 9 (stretch) is using Python 3.5.3 while the f-strings were introduced [in Python 3.6 per docs](https://docs.python.org/3/reference/lexical_analysis.html#f-strings).

```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
```

```
$ python3 --version
Python 3.5.3
```

A temporary fix is to replace that string with old style string replace:

```python
raise ValueError('Units value must be one of %s' % self.UNITS_CODES.keys())
```

**Comment by kasparsd** [comment]
Just noticed that `Pipfile` clearly states that Python 3.7 is required:

https://github.com/h4/lywsd02/blob/d13d013258b1285ed77cd51ef9c4ad940771e071/Pipfile#L12-L13

Not sure why `pip` isn't complaining about it when installing it on Raspbian that doesn't have the required version of Python installed.
